inherit_from: .rubocop_todo.yml

require:
  # - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'config.ru'
    - 'csv_data/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/LineLength:
  Max: 360
  Exclude:
    - 'app/views/home/index_view.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/admin/*'

Metrics/ClassLength:
  Exclude:
    - 'app/mappings/*' # unavoidably large hashes

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - 'app/models/descendent.rb' # case statements

Naming/VariableNumber:
  Exclude:
    - 'app/mappings/*.rb'
    - 'app/services/record_*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false # temporary

RSpec/IndexedLet:
  Enabled: false # uses number sometimes - they can be appropriate

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - and

Style/GuardClause:
  Exclude:
    - 'app/views/**/*'

Style/StringLiterals:
  Exclude:
    - 'Gemfile'


Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Exclude:
    - 'csv_data/**/*'