inherit_from: .rubocop_todo.yml

require:
  # - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - 'db/schema.rb'
    - 'config/initializers/*.rb' # created by installers - leave them be
    - 'app/views/application_view.rb' # temporary it is toooo shit

Layout/LineLength:
  Max: 400

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - 'app/models/descendent.rb' # case statements

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false # temporary

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - and

