module MapElectorateToState
  MAP = {
    # ACT
    'Bean'             => 'ACT',
    'Canberra'         => 'ACT',
    'Fenner'           => 'ACT',

    # NSW
    'Banks'            => 'NSW',
    'Barton'           => 'NSW',
    'Bennelong'        => 'NSW',
    'Berowra'          => 'NSW',
    'Blaxland'         => 'NSW',
    'Bradfield'        => 'NSW',
    'Calare'           => 'NSW',
    'Chifley'          => 'NSW',
    'Cook'             => 'NSW',
    'Cowper'           => 'NSW',
    'Cunningham'       => 'NSW',
    'Dobell'           => 'NSW',
    'Eden-Monaro'      => 'NSW',
    'Farrer'           => 'NSW',
    'Fowler'           => 'NSW',
    'Gilmore'          => 'NSW',
    'Grayndler'        => 'NSW',
    'Greenway'         => 'NSW',
    'Hughes'           => 'NSW',
    'Hume'             => 'NSW',
    'Hunter'           => 'NSW',
    'Kingsford Smith'  => 'NSW',
    'Lindsay'          => 'NSW',
    'Lyne'             => 'NSW',
    'Macarthur'        => 'NSW',
    'Mackellar'        => 'NSW',
    'Macquarie'        => 'NSW',
    'McMahon'          => 'NSW',
    'Mitchell'         => 'NSW',
    'Newcastle'        => 'NSW',
    'New England'      => 'NSW',
    'Page'             => 'NSW',
    'Parkes'           => 'NSW',
    'Parramatta'       => 'NSW',
    'Paterson'         => 'NSW',
    'Reid'             => 'NSW',
    'Richmond'         => 'NSW',
    'Riverina'         => 'NSW',
    'Robertson'        => 'NSW',
    'Shortland'        => 'NSW',
    'Sydney'           => 'NSW',
    'Warringah'        => 'NSW',
    'Watson'           => 'NSW',
    'Wentworth'        => 'NSW',
    'Werriwa'          => 'NSW',
    'Whitlam'          => 'NSW',

    # NT
    'Lingiari'         => 'NT',
    'Solomon'          => 'NT',

    # QLD
    'Blair'            => 'QLD',
    'Bonner'           => 'QLD',
    'Bowman'           => 'QLD',
    'Brisbane'         => 'QLD',
    'Capricornia'      => 'QLD',
    'Dawson'           => 'QLD',
    'Dickson'          => 'QLD',
    'Fadden'           => 'QLD',
    'Fairfax'          => 'QLD',
    'Fisher'           => 'QLD',
    'Flynn'            => 'QLD',
    'Forde'            => 'QLD',
    'Griffith'         => 'QLD',
    'Groom'            => 'QLD',
    'Herbert'          => 'QLD',
    'Hinkler'          => 'QLD',
    'Kennedy'          => 'QLD',
    'Leichhardt'       => 'QLD',
    'Lilley'           => 'QLD',
    'Longman'          => 'QLD',
    'Maranoa'          => 'QLD',
    'McPherson'        => 'QLD',
    'Moncrieff'        => 'QLD',
    'Moreton'          => 'QLD',
    'Oxley'            => 'QLD',
    'Petrie'           => 'QLD',
    'Rankin'           => 'QLD',
    'Ryan'             => 'QLD',
    'Wide Bay'         => 'QLD',
    'Wright'           => 'QLD',

    # SA
    'Adelaide'         => 'SA',
    'Barker'           => 'SA',
    'Boothby'          => 'SA',
    'Grey'             => 'SA',
    'Hindmarsh'        => 'SA',
    'Kingston'         => 'SA',
    'Makin'            => 'SA',
    'Mayo'             => 'SA',
    'Spence'           => 'SA',
    'Sturt'            => 'SA',

    # TAS
    'Bass'             => 'TAS',
    'Braddon'          => 'TAS',
    'Clark'            => 'TAS',
    'Franklin'         => 'TAS',
    'Lyons'            => 'TAS',

    # VIC
    'Aston'            => 'VIC',
    'Ballarat'         => 'VIC',
    'Bendigo'          => 'VIC',
    'Bruce'            => 'VIC',
    'Calwell'          => 'VIC',
    'Casey'            => 'VIC',
    'Chisholm'         => 'VIC',
    'Cooper'           => 'VIC',
    'Corangamite'      => 'VIC',
    'Corio'            => 'VIC',
    'Deakin'           => 'VIC',
    'Dunkley'          => 'VIC',
    'Flinders'         => 'VIC',
    'Fraser'           => 'VIC',
    'Gellibrand'       => 'VIC',
    'Gippsland'        => 'VIC',
    'Goldstein'        => 'VIC',
    'Gorton'           => 'VIC',
    'Hawke'            => 'VIC',
    'Holt'             => 'VIC',
    'Hotham'           => 'VIC',
    'Indi'             => 'VIC',
    'Isaacs'           => 'VIC',
    'Jagajaga'         => 'VIC',
    'Kooyong'          => 'VIC',
    'Lalor'            => 'VIC',
    'La Trobe'         => 'VIC',
    'Macnamara'        => 'VIC',
    'Mallee'           => 'VIC',
    'Maribyrnong'      => 'VIC',
    'McEwen'           => 'VIC',
    'Melbourne'        => 'VIC',
    'Menzies'          => 'VIC',
    'Monash'           => 'VIC',
    'Nicholls'         => 'VIC',
    'Scullin'          => 'VIC',
    'Wannon'           => 'VIC',
    'Wills'            => 'VIC',

    # WA
    'Brand'            => 'WA',
    'Bullwinkel'       => 'WA',
    'Burt'             => 'WA',
    'Canning'          => 'WA',
    'Cowan'            => 'WA',
    'Curtin'           => 'WA',
    'Durack'           => 'WA',
    'Forrest'          => 'WA',
    'Fremantle'        => 'WA',
    'Hasluck'          => 'WA',
    'Moore'            => 'WA',
    "O'Connor"         => 'WA',
    'Pearce'           => 'WA',
    'Perth'            => 'WA',
    'Swan'             => 'WA',
    'Tangney'          => 'WA'
  }.freeze

  def self.lookup(electorate_name)
    MAP[electorate_name]
  end
end
