hard_job:
  cron: '*/5 * * * *'
  class: HardJob
  args:
    - [1, 2, 3]
    - ["string1", "string2"]
    - arg3
ingest_contracts_date:
  cron: '0 2 * * 4' # every week on Thursday at 2am
  class: IngestContractsDateJob